name: fsw_store
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  supabase_flutter: ^1.10.24
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  get: ^4.6.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  flutter_stripe: ^9.5.0+1
  http: ^1.1.0
  intl: ^0.18.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  google_sign_in: ^6.1.6
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  get_storage: ^2.1.1
  readmore: ^2.2.0
  expandable: ^5.0.1
  flutter_animate: ^4.2.0+1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/
    - .env.development
    - .env.production

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/resources/fonts/Poppins/Poppins-Bold.ttf
        - asset: lib/resources/fonts/Poppins/Poppins-Italic.ttf
        - asset: lib/resources/fonts/Poppins/Poppins-Medium.ttf
        - asset: lib/resources/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: lib/resources/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/resources/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: lib/resources/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          style: normal
  
